insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Logica de Programacao','Emerson Carvalho',10);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('MySQL','José Antonio Souza',15);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('JAVA OO','Gabriel Schitz',10);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Codigo Limpo','Roberto Cecil Martin',13);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Python - iniciante','Eric Evans',10);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Nutrição','Steve O.',9);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('As coisas que só você vê','Hermin Carvalho',9);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Drakula - Dark','Matt Ruffes',12);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Frankenstein','Mary Shelly',11);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('O poder da paciencia','M. J. Rayan',9);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('O pequeno principe','Antoine de Saint-Exupéry',8);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('O morro dos ventos uivantes','Emily Bronten',7);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('A garota do lago','Charlie Donlea',11);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Mindset: A nova psicologia do sucesso','Carol S. Dweck e S. Duarte ',14);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('O Peregrino','Jhon Bunyan',6);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Alice no País das Maravilhas',' Lewis Carroll',12);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('A princesa salva a si mesma neste livro','Amanda Lovelace',13);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('O Labirinto Do Fauno','Guillermo Del Toro,',8);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Livro + Bloco criativo (origami)','Maria Angela',12);
insert into armazenamento_livros(Nome_Livro,Autor_Livro,Quantidade_Copias) values('Amor Perfeito','Mariana Sciorilli',10);